[project]
name = "aitheon-cookbook-public"
version = "0.1.0"
description = "GIP cookbook"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["notebook>=7.3.3", "python-dotenv>=1.0.1", "requests>=2.32.3"]
